version: '3'

services:
  rides:
    build:
      context: rides
      dockerfile: Dockerfile
    container_name: rides
    ports:
      - "8000:5000"
    expose:
      - "5000"
    environment:
      TEAM_NAME: "CC_0077_0186_0281"
    depends_on:
      - mongorides

  users:
    build:
      context: users
      dockerfile: Dockerfile
    container_name: users
    ports:
      - "8080:5000"
    expose:
      - "5000"
    environment:
      TEAM_NAME: CC_0077_0186_0281
    depends_on:
      - mongousers

  mongousers:
    image: mongo
    container_name: mongousers
    command: mongod
    expose:
      - "27017"

  mongorides:
    image: mongo
    container_name: mongorides
    command: mongod
    expose:
      - "27017"
